Repository BaekjoonCodingStudy/BaekJoon, pull requests merged in 2024-11, with the labels that each got.

#4 [최원준] Session01
  백준/1번문제/최원준/template.java
Labels: Lang: C/C++, Lang: Java/Kotlin, Lang: Python, Lang: Javascript, 1번 성공, 2번 성공, 3번 성공, 1번 실패, 2번 실패, 3번 실패

#9 Chaehyun
  백준/1번문제/이채현/Q9012.py
  백준/1번문제/이채현/test
  백준/2번문제/이채현/Q10799.py
  백준/2번문제/이채현/test
  백준/3번문제/이채현/test
Labels: Lang: Python, 1번 성공, 2번 성공, 3번 실패

#13 [태현] Session02
  백준/1번문제/태현/Q1620
  백준/1번문제/태현/test
  백준/2번문제/태현/test
  백준/3번문제/태현/test
Labels: Lang: C/C++, 1번 성공, 2번 실패, 3번 실패

#12 Chaehyun
  백준/1번문제/이채현/Q1620.py
  백준/2번문제/Q11286.py
Labels: Lang: Python, 1번 성공, 2번 성공, 3번 실패

#11 [S0okJu] Session02
  백준/1번문제/S0okJu/Q1620.py
  백준/2번문제/S0okJu/Q11286.py
Labels: Lang: Python, 1번 성공, 2번 성공, 3번 실패

#16 [S0okJu] Session03
  백준/1번문제/S0okJu/Q11725.py
  백준/2번문제/S0okJu/Q11286.py
  백준/2번문제/S0okJu/Q1991.py
Labels: Lang: Python, 1번 성공, 2번 성공, 3번 실패

#15 [이채현] Session03
  백준/1번문제/이채현/Q11725.py
  백준/2번문제/이채현/Q11286.py
Labels: Lang: Python, 1번 성공, 2번 실패, 3번 실패

#14 [최원준] Session03
  백준/1번문제/최원준/Q11725.java
  백준/1번문제/최원준/Q1620.java
  백준/1번문제/최원준/Q9012.java
  백준/2번문제/최원준/Q10799.java
  백준/2번문제/최원준/Q11286.java
  백준/2번문제/최원준/Q1991.java
  백준/3번문제/최원준/Q1918.java
  백준/3번문제/최원준/Q1967.java
  백준/3번문제/최원준/Q21942.java
Labels: Lang: Java/Kotlin, Lang: Python, 1번 성공, 2번 성공, 3번 성공

#19 [태현]Session04
  백준/1번문제/태현/Q1747
Labels: Lang: C/C++, 1번 성공, 2번 실패, 3번 실패

#18 [최원준] Session04
  백준/1번문제/최원준/Q2960.java
  백준/2번문제/최원준/Q1747.java
  백준/3번문제/최원준/Q22943.java
Labels: Lang: Java/Kotlin, 1번 성공, 2번 성공, 3번 성공

#17 [S0okJu] Session04
  백준/1번문제/S0okJu/Q2960.py
  백준/2번문제/S0okJu/Q1747.py
  백준/2번문제/S0okJu/Q1991.py
Labels: Lang: Python, 1번 성공, 2번 실패, 3번 실패

#25 [태현] Session05
  백준/2번문제/태현/Q20115
Labels: Lang: C/C++, 2번 성공, 1번 실패, 3번 실패

#24 [S0okJu] Session05
  백준/1번문제/S0okJu/Q2217.py
  백준/2번문제/S0okJu/Q1747.py
  백준/2번문제/S0okJu/Q20115.py
Labels: Lang: Python, 1번 성공, 2번 성공, 3번 실패

#30 [TaeHyun] Session06
  백준/1번문제/태현/Q0655
  백준/2번문제/태현/Q11726
Labels: Lang: C/C++, 1번 성공, 2번 성공, 3번 실패

#28 [S0okJu] Session06
  백준/1번문제/S0okJu/Q2217.py
  백준/1번문제/S0okJu/Q9655.py
Labels: Lang: Python, 1번 성공, 2번 실패, 3번 실패

#27 [최원준] Session06
  백준/1번문제/최원준/Q2217.java
  백준/1번문제/최원준/Q9655.java
  백준/2번문제/최원준/Q11726.java
  백준/2번문제/최원준/Q20115.java
  백준/3번문제/최원준/Q15486.java
  백준/3번문제/최원준/Q2141.java
Labels: Lang: Java/Kotlin, 1번 성공, 2번 성공, 3번 성공

#34 [taetae] Session07
  백준/1번문제/태현/Q15724
Labels: Lang: C/C++, 1번 실패, 2번 실패, 3번 실패

#32 [S0okJu] Session07
  백준/1번문제/S0okJu/Q15724.py
Labels: Lang: Python, 1번 실패, 2번 실패, 3번 실패

#31 [최원준] Session07
  백준/1번문제/최원준/15724-2.py
  백준/2번문제/최원준/2073-2.py
  백준/3번문제/최원준/20542-2.py
Labels: Lang: Python, 1번 성공, 2번 성공, 3번 성공

#37 [taetae] Session08
  백준/1번문제/태현/Q21921
Labels: Lang: C/C++, 1번 실패, 2번 실패, 3번 실패

#36 [최원준] Session08
  백준/1번문제/최원준/Q21921.java
  백준/2번문제/최원준/Q3151.java
Labels: Lang: Java/Kotlin, 1번 성공, 2번 성공, 3번 실패

#41 [taetae] Session09
  백준/1번문제/태현/Q4396
Labels: Lang: C/C++, 1번 성공, 2번 실패, 3번 실패

#39 [S0okJu] Session09
  백준/1번문제/S0okJu/Q15724.py
  백준/2번문제/S0okJu/Q2615.py
Labels: Lang: Python, 1번 실패, 2번 실패, 3번 실패

#38 [최원준] Session09
  백준/1번문제/최원준/Q4396.java
  백준/2번문제/최원준/Q2615.java
  백준/3번문제/최원준/Q14719.java
Labels: Lang: Java/Kotlin, 1번 성공, 2번 성공, 3번 실패
